service: aws-python-http-api-project
frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-python-requirements
custom:
  defaultStage: development
  settings: ${file(env.yml):${self:provider.stage, self:custom.defaultStage}}
  localstack:
    debug: true
    stages:
      - local
  serverless-offline:
    httpPort: 4000
  pythonRequirements:
    layer: true

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, self:custom.defaultStage}
  environment: ${self:custom.settings}

package:
  individually: true
  exclude:
    - node_modules/**
    - .venv/**
    - scripts/**
    - '.gitignore'
    - 'docker-compose.yml'
    - 'README.md'
    - 'package-lock.json'

functions:
  hello:
    handler: src/app.handler
    events:
      - httpApi:
          path: /
          method: post
