service: aws-python-http-api-project
frameworkVersion: '3'

plugins:
  - serverless-offline
custom:
  defaultStage: development
  settings: ${file(env.yml):${self:provider.stage, self:custom.defaultStage}}
  localstack:
    debug: true
    stages:
      - local
  serverless-offline:
    httpPort: 4000

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, self:custom.defaultStage}
  environment: ${self:custom.settings}

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: post
